// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../model/comic.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 935332529679388433),
    name: 'Comic',
    lastPropertyId: const obx_int.IdUid(14, 4376400276972104833),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 22956680624288744),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5668891569503190154),
        name: 'comicId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5296018032108637484),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7231164409951543334),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4667057988559381281),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2718492206471285488),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1890803560762655998),
        name: 'coverPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1330307422816050742),
        name: 'pageCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6063841286740011732),
        name: 'storagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1028731039969690627),
        name: 'chaptersJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6740929189407321853),
        name: 'importedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 484322207293490038),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1746572680421012554),
        name: 'deleted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 418476003968401958),
        name: 'lastReadChapterIndex',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4376400276972104833),
        name: 'lastReadPageIndex',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7819273898175070210),
    name: 'CollectionEntry',
    lastPropertyId: const obx_int.IdUid(4, 7705234950814873537),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5363569434196498127),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3735266202763162136),
        name: 'collectionId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1364501760592668815),
        name: 'comicId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7705234950814873537),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1556473705253692052),
    name: 'FavoriteCollection',
    lastPropertyId: const obx_int.IdUid(5, 5396071608143008388),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7093676685079340763),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2996294707218808527),
        name: 'collectionId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 7774343139297803850),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4877144651049853116),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1641700484661621951),
        name: 'displayOrder',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5396071608143008388),
        name: 'coverPath',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 1556473705253692052),
    lastIndexId: const obx_int.IdUid(2, 7774343139297803850),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Comic: obx_int.EntityDefinition<Comic>(
      model: _entities[0],
      toOneRelations: (Comic object) => [],
      toManyRelations: (Comic object) => {},
      getId: (Comic object) => object.id,
      setId: (Comic object, int id) {
        object.id = id;
      },
      objectToFB: (Comic object, fb.Builder fbb) {
        final comicIdOffset = fbb.writeString(object.comicId);
        final titleOffset = fbb.writeString(object.title);
        final authorOffset = fbb.writeString(object.author);
        final descriptionOffset = fbb.writeString(object.description);
        final coverPathOffset = fbb.writeString(object.coverPath);
        final storagePathOffset = fbb.writeString(object.storagePath);
        final chaptersJsonOffset = fbb.writeString(object.chaptersJson);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, comicIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, authorOffset);
        fbb.addOffset(4, descriptionOffset);
        fbb.addOffset(5, coverPathOffset);
        fbb.addInt64(6, object.pageCount);
        fbb.addOffset(7, storagePathOffset);
        fbb.addOffset(8, chaptersJsonOffset);
        fbb.addInt64(9, object.importedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.displayOrder);
        fbb.addBool(11, object.deleted);
        fbb.addInt64(12, object.lastReadChapterIndex);
        fbb.addInt64(13, object.lastReadPageIndex);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final comicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final coverPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final pageCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final storagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final chaptersJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final importedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final deletedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          26,
          false,
        );
        final lastReadChapterIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final lastReadPageIndexParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final object = Comic(
          id: idParam,
          comicId: comicIdParam,
          title: titleParam,
          author: authorParam,
          description: descriptionParam,
          coverPath: coverPathParam,
          pageCount: pageCountParam,
          storagePath: storagePathParam,
          chaptersJson: chaptersJsonParam,
          importedAt: importedAtParam,
          displayOrder: displayOrderParam,
          deleted: deletedParam,
          lastReadChapterIndex: lastReadChapterIndexParam,
          lastReadPageIndex: lastReadPageIndexParam,
        );

        return object;
      },
    ),
    CollectionEntry: obx_int.EntityDefinition<CollectionEntry>(
      model: _entities[1],
      toOneRelations: (CollectionEntry object) => [],
      toManyRelations: (CollectionEntry object) => {},
      getId: (CollectionEntry object) => object.id,
      setId: (CollectionEntry object, int id) {
        object.id = id;
      },
      objectToFB: (CollectionEntry object, fb.Builder fbb) {
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final comicIdOffset = fbb.writeString(object.comicId);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, collectionIdOffset);
        fbb.addOffset(2, comicIdOffset);
        fbb.addInt64(3, object.displayOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final comicIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = CollectionEntry(
          id: idParam,
          collectionId: collectionIdParam,
          comicId: comicIdParam,
          displayOrder: displayOrderParam,
        );

        return object;
      },
    ),
    FavoriteCollection: obx_int.EntityDefinition<FavoriteCollection>(
      model: _entities[2],
      toOneRelations: (FavoriteCollection object) => [],
      toManyRelations: (FavoriteCollection object) => {},
      getId: (FavoriteCollection object) => object.id,
      setId: (FavoriteCollection object, int id) {
        object.id = id;
      },
      objectToFB: (FavoriteCollection object, fb.Builder fbb) {
        final collectionIdOffset = fbb.writeString(object.collectionId);
        final nameOffset = fbb.writeString(object.name);
        final coverPathOffset = fbb.writeString(object.coverPath);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, collectionIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addInt64(3, object.displayOrder);
        fbb.addOffset(4, coverPathOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final collectionIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final displayOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final coverPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = FavoriteCollection(
          id: idParam,
          collectionId: collectionIdParam,
          name: nameParam,
          displayOrder: displayOrderParam,
          coverPath: coverPathParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Comic] entity fields to define ObjectBox queries.
class Comic_ {
  /// See [Comic.id].
  static final id = obx.QueryIntegerProperty<Comic>(_entities[0].properties[0]);

  /// See [Comic.comicId].
  static final comicId = obx.QueryStringProperty<Comic>(
    _entities[0].properties[1],
  );

  /// See [Comic.title].
  static final title = obx.QueryStringProperty<Comic>(
    _entities[0].properties[2],
  );

  /// See [Comic.author].
  static final author = obx.QueryStringProperty<Comic>(
    _entities[0].properties[3],
  );

  /// See [Comic.description].
  static final description = obx.QueryStringProperty<Comic>(
    _entities[0].properties[4],
  );

  /// See [Comic.coverPath].
  static final coverPath = obx.QueryStringProperty<Comic>(
    _entities[0].properties[5],
  );

  /// See [Comic.pageCount].
  static final pageCount = obx.QueryIntegerProperty<Comic>(
    _entities[0].properties[6],
  );

  /// See [Comic.storagePath].
  static final storagePath = obx.QueryStringProperty<Comic>(
    _entities[0].properties[7],
  );

  /// See [Comic.chaptersJson].
  static final chaptersJson = obx.QueryStringProperty<Comic>(
    _entities[0].properties[8],
  );

  /// See [Comic.importedAt].
  static final importedAt = obx.QueryDateProperty<Comic>(
    _entities[0].properties[9],
  );

  /// See [Comic.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<Comic>(
    _entities[0].properties[10],
  );

  /// See [Comic.deleted].
  static final deleted = obx.QueryBooleanProperty<Comic>(
    _entities[0].properties[11],
  );

  /// See [Comic.lastReadChapterIndex].
  static final lastReadChapterIndex = obx.QueryIntegerProperty<Comic>(
    _entities[0].properties[12],
  );

  /// See [Comic.lastReadPageIndex].
  static final lastReadPageIndex = obx.QueryIntegerProperty<Comic>(
    _entities[0].properties[13],
  );
}

/// [CollectionEntry] entity fields to define ObjectBox queries.
class CollectionEntry_ {
  /// See [CollectionEntry.id].
  static final id = obx.QueryIntegerProperty<CollectionEntry>(
    _entities[1].properties[0],
  );

  /// See [CollectionEntry.collectionId].
  static final collectionId = obx.QueryStringProperty<CollectionEntry>(
    _entities[1].properties[1],
  );

  /// See [CollectionEntry.comicId].
  static final comicId = obx.QueryStringProperty<CollectionEntry>(
    _entities[1].properties[2],
  );

  /// See [CollectionEntry.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<CollectionEntry>(
    _entities[1].properties[3],
  );
}

/// [FavoriteCollection] entity fields to define ObjectBox queries.
class FavoriteCollection_ {
  /// See [FavoriteCollection.id].
  static final id = obx.QueryIntegerProperty<FavoriteCollection>(
    _entities[2].properties[0],
  );

  /// See [FavoriteCollection.collectionId].
  static final collectionId = obx.QueryStringProperty<FavoriteCollection>(
    _entities[2].properties[1],
  );

  /// See [FavoriteCollection.name].
  static final name = obx.QueryStringProperty<FavoriteCollection>(
    _entities[2].properties[2],
  );

  /// See [FavoriteCollection.displayOrder].
  static final displayOrder = obx.QueryIntegerProperty<FavoriteCollection>(
    _entities[2].properties[3],
  );

  /// See [FavoriteCollection.coverPath].
  static final coverPath = obx.QueryStringProperty<FavoriteCollection>(
    _entities[2].properties[4],
  );
}
